name: CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write    

jobs:
  build:
    uses: fruetalo182/github-workflows-templates/.github/workflows/npm-autoversioning-dockerhub.yaml@main
    with:
      node-version: '14'
      docker-hub-image-name: 'wiki-gif'
      docker-hub-username: 'fruetalo'
      docker-build-args: |
        USER=wiki-gif
        GIPHY_API_KEY=${{ secrets.GIPHY_API_KEY }}
    secrets:
      GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
