name: Github Actions Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  execute-lint:
    permissions:
      contents: read
      statuses: write
      pull-requests: read
    uses: fruetalo182/github-workflows-templates/.github/workflows/linter-npm.yaml@main
    secrets: inherit

  versioning: Call reusable versioning workflow
    needs: execute-lint
    uses: fruetalo182/github-workflows-templates/.github/workflows/version-autoupdate-patch.yaml@main

    
  build-push-images:
    needs: execute-lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and push Docker image - Github Packages
        run: |
          docker build --build-arg USER=wiki-gif --build-arg GIPHY_API_KEY=${{ secrets.GIPHY_API_KEY }} -t wiki-gif:${{ github.sha }} .
          echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Tag the image with commit SHA, "latest" and semver
          docker tag wiki-gif:${{ github.sha }} ghcr.io/fruetalo182/wiki-gif:${{ github.sha }}
          docker tag wiki-gif:${{ github.sha }} ghcr.io/fruetalo182/wiki-gif:latest
          docker tag wiki-gif:${{ github.sha }} ghcr.io/fruetalo182/wiki-gif:${{ steps.versioning.outputs.version }}

          # Push all tags to the registry
          docker push ghcr.io/fruetalo182/wiki-gif:${{ github.sha }}
          docker push ghcr.io/fruetalo182/wiki-gif:latest
          docker push ghcr.io/fruetalo182/wiki-gif:${{ steps.versioning.outputs.version }}

      - name: Build and push Docker image - Docker Hub
        run: |
          docker build --build-arg USER=wiki-gif --build-arg GIPHY_API_KEY=${{ secrets.GIPHY_API_KEY }} -t wiki-gif:${{ github.sha }} .
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u fruetalo --password-stdin
          
          # Tag the image with commit SHA, "latest" and semver
          docker tag wiki-gif:${{ github.sha }} fruetalo/wiki-gif:${{ github.sha }}
          docker tag wiki-gif:${{ github.sha }} fruetalo/wiki-gif:latest
          docker tag wiki-gif:${{ github.sha }} fruetalo/wiki-gif:${{ steps.versioning.outputs.version }}

          # Push all tags to the registry
          docker push fruetalo/wiki-gif:${{ github.sha }}
          docker push fruetalo/wiki-gif:latest
          docker push fruetalo/wiki-gif:${{ steps.versioning.outputs.version }}

      - name: Commit and push updated version
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add VERSION
          git commit -m "Increment version to ${{ steps.versioning.outputs.version }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/fruetalo182/wiki-gif.git HEAD:main
