name: Github Actions Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  versioning:
    uses: fruetalo182/github-workflows-templates/.github/workflows/version-autoupdate-patch.yaml@main
    outputs:
      version: ${{ steps.versioning.outputs.version }}

  execute-lint:
    needs: versioning
    permissions:
      contents: read
      statuses: write
      pull-requests: read
    uses: fruetalo182/github-workflows-templates/.github/workflows/linter-npm.yaml@main
    secrets: inherit

  build-push-images:
    needs: [execute-lint, versioning]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and push Docker image - Github Packages
        run: |
          docker build --build-arg USER=wiki-gif --build-arg GIPHY_API_KEY=${{ secrets.GIPHY_API_KEY }} -t wiki-gif:${{ github.sha }} .
          echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Tag the image with commit SHA, "latest" and semver
          docker tag wiki-gif:${{ github.sha }} ghcr.io/fruetalo182/wiki-gif:${{ github.sha }}
          docker tag wiki-gif:${{ github.sha }} ghcr.io/fruetalo182/wiki-gif:latest
          docker tag wiki-gif:${{ github.sha }} ghcr.io/fruetalo182/wiki-gif:${{ needs.versioning.outputs.version }}

          # Push all tags to the registry
          docker push ghcr.io/fruetalo182/wiki-gif:${{ github.sha }}
          docker push ghcr.io/fruetalo182/wiki-gif:latest
          docker push ghcr.io/fruetalo182/wiki-gif:${{ needs.versioning.outputs.version }}

      - name: Build and push Docker image - Docker Hub
        run: |
         
